SELECT naimen FROM USLUGI WHERE stoim BETWEEN 2500 and 4000
SELECT * FROM REMONT WHERE data < '2023-20-01';
SELECT * FROM AVTO WHERE marka LIKE 'Subaru%';
SELECT * FROM AVTO WHERE god = 2009 or god = 2014;
SELECT * FROM REMONT WHERE n_mast LIKE '%2%';
SELECT SUM(sum) FROM REMONT;
SELECT MAX(sum), MIN(sum) FROM REMONT;
SELECT COUNT(n_avto) FROM REMONT;
SELECT n_avto, SUM(sum) FROM REMONT GROUP BY n_avto;
SELECT n_avto, AVG (sum) FROM REMONT GROUP BY n_avto HAVING COUNT (*)>1;